//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaHallSimulation.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        public int TicketId { get; set; }
        public int ShowtimesId { get; set; }
        public int ChairId { get; set; }
        public int Type { get; set; }
        public int UserId { get; set; }
    
        public virtual Chair Chair { get; set; }
        public virtual Showtimes Showtimes { get; set; }
        public virtual User User { get; set; }
    }
}
